### ISSUE TITLE
unable to install with bower

### ISSUE THREAD

**Issue by freegroup** [degt/jquery-morphbutton#1]
Hi

fist of all thanks for your lib!
Unfortunately it is not installable via bower.

```
bower install morphbutton --save
```

may you didn't register your component with the name of your bower.json file.

Greetings
Andreas

**Comment by degt** [comment]
Hi, 

Issue fixed.

Now you can install it via:

```
bower install jquery-morphbutton --save
```

--Daniel G.

**Comment by freegroup** [comment]
:-)
thanks
